(function(){
	var str='';
str+='<div class="gnb-inner">';
str+='<h1 class="logo"><a href="#"><span class="hide">키움투자산운용</span></a></h1>';
str+='           <button type="button" class="btn-prev"><span class="hide">이전</span></button>';
str+='           <h1 class="title hide"></h1>';
str+='           <div class="util">';
str+='               <button type="button" class="btn-sch"><span class="hide">검색</span></button>';
str+='               <button type="button" class="btn-gnb"><span class="hide">전체메뉴 열기</span></button>';
str+='           </div>';
str+='           <div class="gnb-nav" id="gnb">';
str+='               <div class="gnb-header">';
str+='                   <div>';
str+='                       <a href="#none" class="btn-home"><span class="hide">홈</span></a>';
str+='                       <a href="#none" class="btn-global"><span class="hide">영어사이트보기</span></a> ';   
str+='                   </div>';
str+='                   <button type="button" class="btn-close"><span class="hide">전체 메뉴 닫기</span></button>';         
str+='               </div>';
str+='               <div class="gnb">  ';                
str+='                   <ul class="menu">';
str+='                       <li><a href="#">펀드상품</a>    ';                       
str+='                           <ul class="sub">';
str+='                               <li><a href="#">키움펀드맵</a></li>';
str+='                               <li><a href="#">펀드찾기</a></li>';
str+='                               <li><a href="#">분할매수상품</a></li>';
str+='                           </ul>    ';                       
str+='                       </li>';
str+='                       <li><a href="#">연금</a>';
str+='                           <ul class="sub">';
str+='                               <li><a href="#">TDF</a></li>';
str+='                               <li><a href="#">OCIO</a></li>';
str+='                               <li><a href="#">연금펀드</a>';
str+='                               <li><a href="#">연금아카데미</a>';
str+='                                   <ul>';
str+='                                       <li><a href="#">퇴직연금제도</a></li>';
str+='                                       <li><a href="#">개인연금제도</a></li>';
str+='                                       <li><a href="#">연금투자방법</a></li>';
str+='                                       <li><a href="#">MZ 연금레터</a></li>';
str+='                                   </ul>';
str+='                               </li>';
str+='                           </ul>';
str+='                       </li>';
str+='                       <li><a href="#">대체투자</a>';
str+='                           <ul class="sub">';
str+='                               <li><a href="#">REITS</a></li>';
str+='                               <li><a href="#">포트폴리오</a></li>';
str+='                           </ul>';
str+='                       </li>';
str+='                       <li><a href="#">키움라운지</a>';
str+='                           <ul class="sub">';
str+='                               <li><a href="#">회사소개</a></li>';
str+='                               <li><a href="#">투자정보</a>';
str+='                                   <ul>';
str+='                                       <li><a href="#">키자 매거진</a></li>';
str+='                                       <li><a href="#">키자 TV</a></li>';
str+='                                       <li><a href="#">키움 뉴스</a></li>';
str+='                                       <li><a href="#">이벤트</a></li>';
str+='                                   </ul>';
str+='                               </li>';
str+='                               <li><a href="#">책임투자</a>';
str+='                                   <ul>';
str+='                                       <li><a href="#">키움 ESG</a></li>';
str+='                                       <li><a href="#">스튜어드십코드</a></li>';
str+='                                   </ul>';
str+='                               </li>';
str+='                               <li><a href="#">인재채용</a></li>';
str+='                           </ul>';
str+='                       </li>';
str+='                       <li><a href="#">공시</a>';
str+='                           <ul class="sub">';
str+='                               <li><a href="#">경영공시</a></li>';
str+='                               <li><a href="#">펀드공시</a></li>';
str+='                               <li><a href="#">파생공시</a></li>';
str+='                               <li><a href="#">리츠공시</a></li>';
str+='                               <li><a href="#">손실예상금액공시</a></li>';
str+='                               <li><a href="#">연금저축펀드비교공시</a></li>';
str+='                               <li><a href="#">스튜어드십코드공시</a></li>';
str+='                               <li><a href="#">고난도금융투자상품</a></li>';
str+='                           </ul>';
str+='                       </li>';
str+='                   </ul>   ';             
str+='               </div>';
str+='               <div class="gnb-links">';
str+='                   <a href="#" class="btn-company"><span>회사소개</span></a>';
str+='                   <a href="#" class="btn-invest"><span>책임투자</span></a>';
str+='                   <a href="#" class="btn-kosef"><span>KOSEF</span></a>';
str+='               </div>';
str+='           </div>';
str+='        </div>';

document.write(str);

})();

