(function(){
	var str='';

str+='<div class="gnb-nav">';
str+='	<div class="gnb-inner">';
str+='		<h1><a href="#" class="logo"><span class="hide">kosef</span></a></h1>';
str+='		<div class="gnb">';
str+='			<nav>';
str+='				<ul class="menu">';
str+='					<li><a href="#">상품정보</a>    ';                       
str+='						<ul class="sub">';
str+='							<li><a href="#">키움ETF</a></li>';
str+='						</ul>      ';                  
str+='					</li>';
str+='					<li><a href="#">ETF자료실</a>';
str+='						<ul class="sub">';
str+='							<li><a href="#">REPORT</a></li>';
str+='							<li><a href="#">상품별 관련 자료</a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li><a href="#">투자정보</a>';
str+='						<ul class="sub">';
str+='							<li><a href="#">ETF 펀드뉴스</a></li>';
str+='							<li><a href="#">키자매거진&TV</a></li>';
str+='							<li><a href="#">ETF 투자가이드</a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li><a href="#">공시/공지</a>';
str+='						<ul class="sub">';
str+='							<li><a href="#">공시정보</a></li>';
str+='							<li><a href="#">공지/이벤트</a></li>';
str+='							<li><a href="#">FAQ</a></li>';
str+='							<li><a href="#">About KOSEF & 히어로즈</a></li>';
str+='						</ul>';
str+='					</li>';
str+='				</ul>  ';            
str+='			</nav>';
str+='		</div>';
str+='		<div class="util">';
str+='			<a href="#" class="go-kiam">키움투자자산운용</a>	';		
str+='			<a href="#" class="go-eng"><span>ENG</span></a>';	
str+='			<div class="top-sch-group">';
str+='				<button class="btn-sch"><span class="hide">검색</span></button>';
str+='				<div class="sch-cont" tabindex="-1">';
str+='					<div class="search-area">';
str+='						<div class="sch-top">';
str+='						<input type="text" class="inp-base" data-clear="true" placeholder="검색어를 입력하세요." title="검색어 입력"> ';
str+='						<button class="btn-sch"><span class="hide">검색</span></button>';
str+='						</div>';
str+='					</div>';
str+='					<button type="button" class="btn-close"><span class="hide">닫기</span></button>';
str+='				</div>';
str+='			</div>';
str+='		</div>';
str+='	</div>';
str+='	<div class="gnb-bg"></div>';
str+='</div>';

// str+='	<div class="gnb-top">';
// str+='    <ul class="links">';
// str+='        <li><a href="#">회사소개</a></li>';
// str+='        <li class="current"><a href="#">키움자산운용</a></li>';
// str+='        <li><a href="#">KOSEF</a></li>';
// str+='    </ul>';
// str+='    <div class="global ui-drop-wrap" id="globalToggle">';
// str+='       <a href="#" class="ui-drop-btn"><span>KR</span></a>';
// str+='       <div>';
// str+='            <ul class="ui-drop-box">';
// str+='                <a href="#">KR</a>';
// str+='                <a href="#">EN</a>';
// str+='            </ul>   ';
// str+='       </div>';
// str+='    </div>';
// str+='</div>';
// str+=' <div class="gnb-nav">';
// str+='                <div class="gnb-inner">';
// str+='                    <h1><a href="#" class="logo"><span class="hide">kosef</span></a></h1>';
// str+='                    <div class="gnb">';
// str+='                        <nav>';
// str+='                            <ul class="menu">';
// str+='                                <li><a href="#">상품정보</a>      ';                     
// str+='                                    <ul class="sub">';
// str+='                                        <li><a href="#">키움ETF</a></li>';
// str+='                                    </ul>   ';                     
// str+='                                </li>';
// str+='                                <li><a href="#">ETF자료실</a>';
// str+='                                    <ul class="sub">';
// str+='                                        <li><a href="#">REPORT</a></li>';
// str+='                                        <li><a href="#">상품별 관련 자료</a></li>';
// str+='                                    </ul>';
// str+='                                </li>';
// str+='                                <li><a href="#">투자정보</a>';
// str+='                                    <ul class="sub">';
// str+='                                        <li><a href="#">ETF 펀드뉴스</a></li>';
// str+='                                        <li><a href="#">키자매거진&TV</a></li>';
// str+='                                        <li><a href="#">ETF 투자가이드</a></li>';
// str+='                                    </ul>';
// str+='                                </li>';
// str+='                                <li><a href="#">공시/공지</a>';
// str+='                                    <ul class="sub">';
// str+='                                        <li><a href="#">공시정보</a></li>';
// str+='                                        <li><a href="#">공지/이벤트</a></li>';
// str+='                                        <li><a href="#">FAQ</a></li>';
// str+='                                        <li><a href="#">About KOSEF & 히어로즈</a></li>';
// str+='                                    </ul>';
// str+='                                </li>';
// str+='                            </ul>  ';            
// str+='                        </nav>';
// str+='                    </div>';
// str+='                    <div class="util">';
// str+='                        <a href="#" class="go-kiam">키움투자자산운용</a>';                 
// str+='                    	  <a href="#" class="go-global"><span>ENG</span></a>';
// str+='                    </div>';
// str+='                    <div class="top-sch-group">';
// str+='                        <button class="btn-sch"><span class="hide">검색</span></button>';
// str+='                            <div class="sch-cont" tabindex="-1">';
// str+='                                <div class="search-area">';
// str+='                                    <div class="sch-top">';
// str+='                                        <input type="text" class="inp-base" data-clear="true" placeholder="검색어를 입력하세요." title="검색어 입력"> ';
// str+='                                        <button class="btn-sch"><span class="hide">검색</span></button>';
// str+='                                    </div>';
// str+='                                </div>';
// str+='                                <button type="button" class="btn-close"><span class="hide">닫기</span></button>';
// str+='                            </div>';
// str+='                        </div>';
// str+='                    </div>';
// str+='                </div>';
// str+='                <div class="gnb-bg"></div>';
// str+='            </div>';
	document.write(str);
})();

