/**
* 다이렉트 보험 서비스 플랫폼 구축
* ------------------------------
* footer.js
*/


/*(function(){
	var str=''
		+'		<!-- footer -->'
		+'		<div id="footer">'
		+'			<div class="footer_section">'
		+'				<ul class="footer_menu">'
		+'					<li><a href="javascript:void(0);">홈페이지 이용약관</a></li>'
		+'					<li><a href="javascript:void(0);">전자금융거래 이용약관</a></li>'
		+'				</ul>'
		+'				<ul class="footer_info">'
		+'					<li>현대해상화재보험(주)</li>'
		+'					<li>대표이사 조용일&middot;이성재</li>'
		+'					<li>사업자등록번호 102-81-32035</li>'
		+'					<li>(03183) 서울특별시 종로구 세종대로 163, 현대해상빌딩(세종로)</li>'
		+'				</ul>'
		+'				<p class="copyright">Copyright Hyundai Marine &amp; Fire Insurance Co., Ltd. All rights reserved.</p><!-- 11/1: 수정 (CG059) -->'
		+'			</div>'
		+'		</div>'
		+'		<!-- //footer -->'


	document.write(str);
})();
*/




(function(){
	var str=''
	+'		<!--footerWrap : s-->'
	// +'<div id="footer">'
	+'		<div class="footerWrap">'
	+'			<div class="footerCustomerArea" id="etcInsurance">'
	+'				<div class="footerCustomer">'
	+'					<div class="telInfo">'
	+'						<p class="txt">고객콜센터</p>'
	+'						<p class="tel">1899-<span class="fontPoint5">6782</span></p><!-- 202209 접근성22번 -->'
	+'						<p class="time">(고장출동 24시간)</p>'
	+'					</div>'
	+'					<ul class="infoTxt">'
	+'						<li><span class="fontBase">자동차보험 산출/가입상담</span> <span class="fontPoint5">(ARS 1번)</span> 평일 09:00 ~ 18:00</li><!-- 202209 접근성22번 -->'
	+'						<li><span class="fontBase">장기·일반보험 가입상담/계약변경</span> <span class="fontPoint1">(ARS 3번)</span> 평일 09:00 ~ 18:00</li>'
	+'					</ul>'
	+'				</div>'
	+'			</div>'
	+'			<div class="footerArea">'
	+'				<div class="infoArea">'
	+'					<ul class="footerMenu">'
	+'						<li>'
	+'							<a href="https://qa.hi.co.kr/serviceAction.do?menuId=100991" target="_blank" title="개인정보처리방침(개인정보보호법)" class="point">개인정보처리방침(개인정보보호법)</a>'
	+'						</li>'
	+'						<!--2021.04.07 R20210406-0047로 제거, 심흥무  li><a href="https://www.hi.co.kr/bin/CI/ON/CION3751G.jsp" target="_blank" title="개인정보처리방침(정보통신망법)" class="point">개인정보처리방침(정보통신망법)</a></li>-->'
	+'						<li>'
	+'							<a href="https://qa.hi.co.kr/serviceAction.do?menuId=100994" target="_blank" title="고객권리안내문">고객권리안내문</a>'
	+'						</li>'
	+'						<li>'
	+'							<a href="https://qa.hi.co.kr/serviceAction.do?menuId=100989" target="_blank" title="보호금융상품등록부">보호금융상품등록부</a>'
	+'						</li>'
	+'						<li>'
	+'							<a href="https://qa.hi.co.kr/serviceAction.do?menuId=100950" target="_blank" title="가격공시">가격공시</a>'
	+'						</li>'
	+'					</ul>'
	+'					<div class="footerTxt">'
	+'						현대해상화재보험㈜ <span class="line"></span> 대표이사 조용일 · 이성재 <span class="line"></span> 사업자등록번호 102-81-32035<br>'
	+'						(03183) 서울특별시 종로구 세종대로 163, 현대해상빌딩(세종로)'
	+'						<p class="copyright">Copyright ⓒ Hyundai Marine &amp; Fire Insurance Co.,Ltd. All right reserved.</p>'
	+'					</div>'
	+'					<ul class="snsArea">'
	+'						<li><a href="https://www.facebook.com/hi.co.kr" target="_blank" title="페이스북 바로가기"><img src="https://direct.hi.co.kr/images/common/ic_footer_sns01.png" alt="페이스북 바로가기"></a></li>'
	+'						<li><a href="http://blog.hi.co.kr" target="_blank" title="블로그 바로가기"><img src="https://direct.hi.co.kr/images/common/ic_footer_sns02.png" alt="블로그 바로가기"></a></li>'
	+'						<li><a href="https://blog.naver.com/goodngoodblog" target="_blank" title="어린이블로그 바로가기"><img src="https://direct.hi.co.kr/images/common/ic_footer_sns04.png" alt="어린이블로그 바로가기"></a></li>'
	+'						<li><a href="http://blog.naver.com/direct_hi" target="_blank" title="다이렉트블로그 바로가기"><img src="https://direct.hi.co.kr/images/common/ic_footer_sns03.png" alt="다이렉트블로그 바로가기"></a></li>'
	+'						<li><a href="https://story.kakao.com/ch/hiheart" target="_blank" title="카카오스토리 바로가기"><img src="https://direct.hi.co.kr/images/common/ic_footer_sns05.png" alt="카카오스토리 바로가기"></a></li>'
	+'						<li><a href="https://www.youtube.com/user/HicarHilife" target="_blank" title="유튜브 바로가기"><img src="https://direct.hi.co.kr/images/common/ic_footer_sns06.png" alt="유튜브 바로가기"></a></li>'
	+'					</ul>'
	+'				</div>'
	+'				<!-- // infoArea -->'
	+'				<div class="callArea">'
	+'					<div class="callCt">'
	+'						<p class="txTi">'
	+'							<strong><a href="/service.do?m=47f30812bf&amp;tagtype=9&amp;_BT_tab=CALD0001&amp;inpath=MB">다이렉트 고객센터</a></strong>'
	+'							<span>인터넷가입/계약변경</span>'
	+'						</p>'
	+'						<div class="txCall">'
	+'							<strong class="cOrg">1899-6782</strong>'
	+'							<span>(평일9시~18시)</span>'
	+'						</div>'
	+'					</div>'
	+'					<div class="callCt">'
	+'						<p class="txTi">'
	+'							<strong><a href="/service.do?m=47f30812bf&amp;tagtype=9&amp;_BT_tab=CALD0002&amp;inpath=MB#phone_product">전화가입상담센터</a></strong>'
	+'							<span>자동차보험 전화가입</span>'
	+'						</p>'
	+'						<div class="txCall">'
	+'							<strong class="cBlue">1577-1001</strong>'
	+'							<span>(평일9시~18시)</span>'
	+'						</div>'
	+'					</div>'
	+'				</div>'
	+'				<!-- // callArea -->'
	+'			</div>'
	+'			<!-- // footerArea -->'
	+'			<div class="awardArea">'
	+'				<ul class="bottomLogo">'
	+'					<li><a href="/service.do?ntceSeqno=257&amp;m=90b5c23cb2" target="_self"><img src="https://direct.hi.co.kr/images/common/ic_footer_award01.gif" alt="한국산업의 브랜드파워 1위"></a></li>'
	+'					<li><img src="https://direct.hi.co.kr/images/common/ic_footer_award03.gif" alt="우수콜센터 10년연속 인증"></li>'
	+'					<li><a href="/service.do?ntceSeqno=279&amp;m=90b5c23cb2"><img src="https://direct.hi.co.kr/images/common/ic_footer_award04.gif" alt="앱어워드코리아 다이렉트보험부분 대상"></a></li>'
	+'					<li><a href="/service.do?ntceSeqno=266&amp;m=90b5c23cb2"><img src="https://direct.hi.co.kr/images/common/ic_footer_award05.gif" alt="글로벌 고객만족도조사"></a></li>'
	+'					<li><a href="/file/pdf/isms2022.pdf" target="_blank"><img src="https://direct.hi.co.kr/images/common/ic_footer_award09.gif" alt="정보보호 관리체계 인증"></a></li>'
	+'					<li><a href="/file/pdf/wa.pdf" target="_blank" title="새창 열림"><img src="https://direct.hi.co.kr/images/common/ic_footer_award10.gif" alt="웹접근성 인증"></a></li>'
	+'				</ul>'
	+'			</div>'
	+'			<!-- // awardArea -->'
	+'		</div>'
	+'		<!--footerWrap : e-->'

	
	// +'</div>'
	
	document.write(str);
})();

