/**
* 다이렉트 보험 서비스 플랫폼 구축
* ------------------------------
* gnb.js
* ------------------------------
* [3/7: 수정] //subMenuAreaWrap 추가
*/


(function(){
	var str=''
		+'<!--gnbWrapSet : s-->'
		+'<div class="gnbWrapSet fixed" id="gnb">'
		+'	<div class="gnbWrap "><!-- 202106 -->'
		+'		<div class="gnbArea">'
		+'			<h1 class="logo">'
		+'				<a href="/service.do?m=3293e8e708" title="메인페이지로 이동">'
		+'					<img src="https://direct.hi.co.kr/images/common/homepage_logo_01.png" alt="현대해상 다이렉트" class="logo1" style="display: none;"><img src="https://direct.hi.co.kr/images/common/homepage_logo_02.png" alt="현대해상 다이렉트" class="logo2" style="display: block;">'
		+'				</a>'
		+'			</h1>'

		// =======================================
		// * topmenu
		// =======================================
		+'			<div class="topmenu">'
		+'			<div class="topmenuWrap">' //[3/7: 수정]
		+'				<ul class="menu">'
		+'					<!-- <li><a href="/service.do?m=fdaf815390">모바일 서비스</a></li>'
		+'					<li><a href="/service.do?m=df1f1b2f16">고객센터</a></li>'
		+'					<li><a href="/service.do?m=34b8e0f086">이벤트</a></li> -->'
		+'					<li><a href="#" target="_blank" title="새창으로 열림">상품공시</a></li>'
		+'					<li><a href="#" target="_blank" title="새창으로 열림">현대해상 홈페이지</a></li>'
		+'				</ul>'
		+'				<div class="type">'
		+'					<a title="개인 자동차보험료 계산하기" href="#">개인</a>'
		+'					<a title="법인 자동차보험료 계산하기" href="#">법인</a>'
		+'				</div>'
		+'				<a href="#" class="btnAllmenu"><img src="https://direct.hi.co.kr/images/common/btn_allmenu_off.png" alt="전체메뉴보기"></a>'
		+'				<!-- 전체메뉴 시작 -->'
		+'				<!--allmenuListArea : s-->'
		+'				<div class="allmenuListArea">'
		+'					<div class="allmenuList">'
		+'						<ul>'
		+'							<!-- 1레벨 -->'
		+'							<li><a href="/service.do?m=e429f6a022" class="dep1">보험상품</a>'
		+'								<div class="dep2">'
		+'									<ul>'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=2010000000">자동차</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=e429f6a022">자동차보험(개인)</a></li>'
		+'												<li><a href="/service.do?m=22dd052071">자동차보험(법인)</a></li>'
		+'												<li><a href="/service.do?m=f0d5fd1b1a">이륜차보험</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">건강/어린이</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=9647788f37">어린이보험</a></li>'
		+'												<li><a href="/service.do?m=52c7dc3407">건강보험</a></li>'
		+'												<li><a href="/service.do?m=27730ddeeb">암보험</a></li>'
		+'												<li><a href="/service.do?m=1a9d7b3cd8">실손의료비보험</a></li>'
		+'												<li><a href="/service.do?m=f4bf528abe">실손의료비보험(계약전환용)</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=7435d816d2">여행/레저/펫</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=7435d816d2">해외여행보험</a></li>'
		+'												<li><a href="/service.do?m=0bf9f0b074">해외장기체류보험</a></li>'
		+'												<li><a href="/service.do?m=e2261df365">국내여행보험</a></li>'
		+'												<li><a href="/service.do?m=74b0e768bb">골프보험</a></li>'
		+'												<li><a href="/service.do?m=b4271ce25f">하이펫보험</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">운전자/생활</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=38fdd650f4">운전자보험</a></li>'
		+'												<li><a href="/service.do?m=6c628f36be">주택화재상해보험</a></li>'
		+'												<li><a href="/service.do?m=8bb8a827c6">사업장화재보험</a></li>'
		+'												<li><a href="/service.do?m=71ca2c6649">연금보험(유배당)</a></li>'
		+'												<li><a href="/service.do?m=028383e51e">하이로연금보험(유배당)</a></li>'
		+'												<li><a href="/service.do?m=77c6555e20">풍수해보험(주택용)</a></li>'
		+'												<li><a href="/service.do?m=c587727700"> 풍수해보험(소상공인)</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">전화가입상품</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=a42a081f35">자동차보험</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929010">운전자보험</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929020">종합건강보험</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929000">어린이보험</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929030">암보험</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929040">치아보험</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929050">유병자 건강보험</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'									</ul>'
		+'								</div>'
		+'							</li>'
		+'							<!-- 레벨 1 e-->'
		+'							<!-- 1레벨 -->'
		+'							<li><a href="." class="dep1">MY다이렉트</a>'
		+'								<div class="dep2">'
		+'									<ul>'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">계약확인 및 개인정보변경</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100101">계약조회</a></li>'
		+'												<li><a href="/service.do?m=888c3b8b63">고객정보 확인/변경</a></li>'
		+'												<li><a href="/service.do?m=73a2a20d85">마케팅정보 활용 동의,철회 </a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">보험 계약변경</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=8dc866b098">자동차보험 계약변경</a></li>'
		+'												<li><a href="/service.do?m=eb99e26059">장기보험 계약변경</a></li>'
		+'												<li><a href="/service.do?m=f72d44b318">일반보험 계약변경<br>(여행,레저,펫,풍수해)</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100611" target="_blank" title="새창으로">증명서발급</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100611" target="_blank" title="새창으로">보험증권</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100615" target="_blank" title="새창으로">보험료납입증명서</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100616" target="_blank" title="새창으로">자동차보험가입증명서</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100616">적용요율등급확인서</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100616">교통사고피해확인서</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100614">보험금지급내역서</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">보험계약대출</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100302&amp;tagtype=9&amp;_BT_tab=GNBL0001&amp;inpath=MB" target="_blank" title="새창으로">보험계약대출 신청</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100303&amp;tagtype=9&amp;_BT_tab=GNBL0002&amp;inpath=MB" target="_blank" title="새창으로">보험계약대출 상환</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100304&amp;tagtype=9&amp;_BT_tab=GNBL0003&amp;inpath=MB" target="_blank" title="새창으로">이자납입계좌 변경</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100305&amp;tagtype=9&amp;_BT_tab=GNBL0004&amp;inpath=MB" target="_blank" title="새창으로">보험계약대출 거래내역조회</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'									</ul>'
		+'								</div>'
		+'							</li>'
		+'							<!-- 레벨 1 e-->'
		+'							<!-- 1레벨 -->'
		+'							<li><a href="/service.do?m=43e7038139" class="dep1">보상/청구</a>'
		+'								<div class="dep2">'
		+'									<ul>'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=43e7038139">자동차사고/고장 접수</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=43e7038139">사고접수안내</a></li>'
		+'												<li><a href="/service.do?m=19416bba17">보험금청구서류</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100521" target="_blank" title="새창으로">고장출동서비스</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100441" target="_blank" title="새창으로">교통사고처리요령</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#" target="_blank" title="새창으로">보상상담</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100443" target="_blank" title="새창으로">자동차보험 사고처리 유불리</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=d3a09d35d0">보험금 청구</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=d3a09d35d0">보험금청구안내</a></li>'
		+'												<li><a href="/service.do?m=d3a09d35f0">보험금청구서류</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'									</ul>'
		+'								</div>'
		+'							</li>'
		+'							<!-- 레벨 1 e-->'
		+'							<!-- 1레벨 -->'
		+'							<li><a href="/service.do?m=e014084a3d " class="dep1">혜택/이벤트</a>'
		+'								<div class="dep2">'
		+'									<ul>'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=58ddb3faf8">이달의 카드 할인/혜택</a></li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=98d21e6e26">포인트 결제</a></li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=34b8e0f086">이벤트</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=93b203359">진행중 이벤트</a></li>'
		+'												<li><a href="/service.do?m=fe51010287">당첨자 안내</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=1a4f675719">제휴사 할인/서비스</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=00a66ac167">오토오아시스</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=7a52bef8bc">따뜻한 나눔</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=5b7d8a9c4a">기부하기</a></li>'
		+'												<li><a href="/service.do?m=6999017849">기부결과</a></li>'
		+'												<li><a href="/service.do?m=7044dbb403">기부처소개</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=4215401386">다이렉트 TV</a></li>'
		+'										<!-- 레벨 2 e-->'
		+'									</ul>'
		+'								</div>'
		+'							</li>'
		+'							<!-- 레벨 1 e-->'
		+'							<!-- 1레벨 -->'
		+'							<li><a href="/service.do?m=df1f1b2f16" class="dep1">고객센터</a>'
		+'								<div class="dep2">'
		+'									<ul>'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">고객의 소리</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=304e3b0d8e">고객체험후기</a></li>'
		+'												<li><a href="/service.do?m=fc452654c6">이메일 상담신청</a></li>'
		+'												<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=101451">전자민원 접수</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">고객 안내사항</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=b79d5eefe8">FAQ (자주 묻는 질문)</a></li>'
		+'												<li><a href="/service.do?m=1dc3a3a380">공지사항</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">모바일 이용안내</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=fdaf815390">모바일 서비스</a></li>'
		+'												<li><a href="/service.do?m=47f30812c0">보험료계산 가이드</a></li>'
		+'												<li><a href="/service.do?m=47f30812c1">보안프로그램 설치 및 안내</a></li>'
		+'												<li><a href="/service.do?m=b11cacddee">공동인증서 이용안내</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=47f30812bf">고객콜센터 안내</a></li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="/service.do?m=bfda6eb660">상담원 채용</a></li>'
		+'										<!-- 레벨 2 e-->'
		+'										<!-- 레벨 2 s-->'
		+'										<li><a href="#">홈페이지 이용안내</a>'
		+'											<ul class="dep3">'
		+'												<li><a href="/service.do?m=f783053a96">보험료계산 가이드</a></li>'
		+'												<li><a href="/service.do?m=1e5bcd6ec7">실시간 상담 신청 가이드</a></li>'
		+'												<li><a href="/service.do?m=6799759c25">보안프로그램 설치 및 안내</a></li>'
		+'												<li><a href="/service.do?m=47f30812c2">전자금융거래 유의사항</a></li>'
		+'											</ul>'
		+'											<!-- 레벨 3 e-->'
		+'										</li>'
		+'										<!-- 레벨 2 e-->'
		+'									</ul>'
		+'								</div>'
		+'							</li>'
		+'						<!-- 레벨 1 e-->'
		+'						</ul>'
		+'					</div>'
		+'				</div>'
		+'				<!--allmenuListArea : e-->'
		+'				<!-- 전체메뉴 끝 -->'
		+'			</div>'//[3/7: 수정], topmenuWrap
		+'			</div>'


		// =======================================
		// * GNB
		// =======================================

		+'			<ul class="gnb" id="gnb">'
		+'				<li>'
		+'					<a href="/service.do?m=e429f6a022">보험</a>'
		+'					<!--subMenuArea : s-->'
		+'					<div class="subMenuArea sub1" style="display: none;">'

		+'					<div class="subMenuAreaWrap">'//[3/7: 수정]

		+'						<div class="submenuTitle">'
		+'							<p class="tit">보험상품</p>'
		+'							<p class="txt">365일, 24시간 언제든지<br>인터넷으로 쉽고 빠르게!</p>'
		+'							<!--  strong><a href="/service.do?m=e429f6a022"  ><img src="https://direct.hi.co.kr/images/common/gnb_01_1.gif" alt="365일, 24시간 언제든지<br>인터넷으로 쉽고 빠르게!" /></a></strong  -->'
		+'						</div>'
		+'						<ul class="gnb_dep2 many">'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=2010000000">자동차</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=e429f6a022"><span>자동차보험(개인)</span></a>'
		+'										<ul class="listStyle bar pl20 pb20 noGap">'
		+'											<li><a href="/service.do?m=e429f6a022&amp;innerTab=1">자녀할인 특약</a></li>'
		+'											<li><a href="/service.do?m=e429f6a022&amp;innerTab=2">ECO 마일리지 특약</a></li>'
		+'											<li><a href="/service.do?m=e429f6a022&amp;innerTab=3">블랙박스 장착특약</a></li>'
		+'											<li><a href="/service.do?m=e429f6a022&amp;innerTab=4">커넥티드카 할인 특약</a></li>'
		+'											<li><a href="/service.do?m=e429f6a022&amp;innerTab=5">커넥티드카안전운전(UBI) 할인 특약</a></li>'
		+'											<li><a href="/service.do?m=e429f6a022&amp;innerTab=6">차선이탈 경고장치 할인 특약</a></li>'
		+'											<li><a href="/service.do?m=e429f6a022&amp;innerTab=7">전방충돌 경고장치 할인 특약</a></li>'
		+'										</ul>'
		+'									</li>'
		+'									<li><a href="/service.do?m=22dd052071"><span>자동차보험(법인)</span></a></li>'
		+'									<li><a href="/service.do?m=f0d5fd1b1a"><span>이륜차보험</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="#">건강/어린이</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=9647788f37"><span>어린이보험</span></a></li>'
		+'									<li><a href="/service.do?m=52c7dc3407"><span>건강보험</span></a></li>'
		+'									<li><a href="/service.do?m=27730ddeeb"><span>암보험</span></a></li>'
		+'									<li><a href="/service.do?m=1a9d7b3cd8"><span>실손의료비보험</span></a></li>'
		+'									<li><a href="/service.do?m=f4bf528abe"><span>실손의료비보험(계약전환용)</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=7435d816d2">여행/레저/펫</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=7435d816d2"><span>해외여행보험</span></a></li>'
		+'									<li><a href="/service.do?m=0bf9f0b074"><span>해외장기체류보험</span></a></li>'
		+'									<li><a href="/service.do?m=e2261df365"><span>국내여행보험</span></a></li>'
		+'									<li><a href="/service.do?m=74b0e768bb"><span>골프보험</span></a></li>'
		+'									<li><a href="/service.do?m=b4271ce25f"><span>하이펫보험</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="#">운전자/생활</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=38fdd650f4"><span>운전자보험</span></a></li>'
		+'									<li><a href="/service.do?m=6c628f36be"><span>주택화재상해보험</span></a></li>'
		+'									<li><a href="/service.do?m=8bb8a827c6"><span>사업장화재보험</span></a></li>'
		+'									<li><a href="/service.do?m=71ca2c6649"><span>연금보험(유배당)</span></a></li>'
		+'									<li><a href="/service.do?m=028383e51e"><span>하이로연금보험(유배당)</span></a></li>'
		+'									<li><a href="/service.do?m=77c6555e20"><span>풍수해보험(주택용)</span></a></li>'
		+'									<li><a href="/service.do?m=c587727700"><span> 풍수해보험(소상공인)</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="#">전화가입상품</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=a42a081f35"><span>자동차보험</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929010"><span>운전자보험</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929020"><span>종합건강보험</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929000"><span>어린이보험</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929030"><span>암보험</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929040"><span>치아보험</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=929050"><span>유병자 건강보험</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'						</ul>'
		+'						<!-- bannerCall -->'
		+'						<div class="gnBnCall ic_internet">'
		+'							<div class="callCt">'
		+'								<p class="txTi">'
		+'								<strong>다이렉트 고객센터</strong>'
		+'								<span>인터넷가입/계약변경</span>'
		+'								</p>'
		+'								<div class="txCall">'
		+'								<strong class="cOrg">1899</strong><strong class="cBlue">-6782</strong>'
		+'								<span>(평일9시~18시)</span>'
		+'								</div>'
		+'							</div>'
		+'						</div>'
		+'						<!-- GNB 보험상품 전화가입상담센터 추가 : s -->'
		+'						<div class="gnBnCall ic_tel" style="margin-top:210px;">'
		+'							<div class="callCt">'
		+'								<p class="txTi">'
		+'									<strong>전화가입 상담센터</strong>'
		+'									<span>자동차보험 전화가입</span>'
		+'								</p>'
		+'								<div class="txCall">'
		+'									<strong class="cOrg">1577</strong><strong class="cBlue">-1001</strong>'
		+'									<span>(평일9시~18시)</span>'
		+'								</div>'
		+'							</div>'
		+'						</div>'
		+'						<!--// GNB 보험상품 전화가입상담센터 추가 : e -->'
		+'						<!-- // bannerCall -->'
		+'					</div>'//[3/7: 수정] //subMenuAreaWrap
		+'					</div>'
		+'					<!--subMenuArea : e-->'
		+'				</li>'

		+'				<li>'
		+'					<a href="/service.do?m=b2265d8cb3">마이</a>'
		+'					<!--subMenuArea : s-->'
		+'					<div class="subMenuArea sub2" style="display: none;">'
		+'					<div class="subMenuAreaWrap">'//[3/7: 수정]
		+'						<div class="submenuTitle">'
		+'							<p class="tit">MY다이렉트</p>'
		+'							<p class="txt">보험계약 관리도<br>인터넷으로 쉽고 편리하게!<br><br><span class="fontPoint2 fz14">※계약자의 공동인증서가 필요합니다</span></p>'
		+'							<!--  strong><a href="/service.do?m=b2265d8cb3"  ><img src="https://direct.hi.co.kr/images/common/gnb_05_1.gif" alt="보험계약 관리도<br>인터넷으로 쉽고 편리하게!<br><br><span class="fontPoint2 fz14">※계약자의 공동인증서가 필요합니다</span>" /></a></strong  -->'
		+'						</div>'
		+'						<ul class="gnb_dep2">'
		+'							<li><a href="#">계약확인 및 개인정보변경</a>'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100101"><span>계약조회</span></a></li>'
		+'									<li><a href="/service.do?m=888c3b8b63"><span>고객정보 확인/변경</span></a></li>'
		+'									<li><a href="/service.do?m=73a2a20d85"><span>마케팅정보 활용 동의,철회 </span></a></li>'
		+'								</ul>'
		+'							</li>'
		+'							<li><a href="#">보험 계약변경</a>'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=8dc866b098"><span>자동차보험 계약변경</span></a></li>'
		+'									<li><a href="/service.do?m=eb99e26059"><span>장기보험 계약변경</span></a></li>'
		+'									<li><a href="/service.do?m=f72d44b318"><span>일반보험 계약변경<br>(여행,레저,펫,풍수해)</span></a></li>'
		+'								</ul>'
		+'							</li>'
		+'							<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100611" target="_blank" title="새창으로">증명서발급</a>'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100611" target="_blank" title="새창으로"><span>보험증권</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100615" target="_blank" title="새창으로"><span>보험료납입증명서</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100616" target="_blank" title="새창으로"><span>자동차보험가입증명서</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100616"><span>적용요율등급확인서</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100616"><span>교통사고피해확인서</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100614"><span>보험금지급내역서</span></a></li>'
		+'								</ul>'
		+'							</li>'
		+'						</ul>'
		+'						<ul class="gnb_dep2 many">'
		+'							<li><a href="#">보험계약대출</a>'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100302&amp;tagtype=9&amp;_BT_tab=GNBL0001&amp;inpath=MB" target="_blank" title="새창으로"><span>보험계약대출 신청</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100303&amp;tagtype=9&amp;_BT_tab=GNBL0002&amp;inpath=MB" target="_blank" title="새창으로"><span>보험계약대출 상환</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100304&amp;tagtype=9&amp;_BT_tab=GNBL0003&amp;inpath=MB" target="_blank" title="새창으로"><span>이자납입계좌 변경</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100305&amp;tagtype=9&amp;_BT_tab=GNBL0004&amp;inpath=MB" target="_blank" title="새창으로"><span>보험계약대출 거래내역조회</span></a></li>'
		+'								</ul>'
		+'							</li>'
		+'						</ul>'
		+'						<!-- bannerCall -->'
		+'						<div class="gnBnCall ic_internet">'
		+'							<div class="callCt">'
		+'								<p class="txTi">'
		+'									<strong>다이렉트 고객센터</strong>'
		+'									<span>인터넷가입/계약변경</span>'
		+'								</p>'
		+'								<div class="txCall">'
		+'									<strong class="cOrg">1899</strong><strong class="cBlue">-6782</strong>'
		+'									<span>(평일9시~18시)</span>'
		+'								</div>'
		+'							</div>'
		+'						</div>'
		+'						<!-- // bannerCall -->'
		+'					</div>'
		+'					</div>'//[3/7: 수정] //subMenuAreaWrap
		+'					<!--subMenuArea : e-->'
		+'				</li>'

		// +'				<li>'
		// +'					<a href="/service.do?m=43e7038139">보상/청구</a>'
		// +'					<!--subMenuArea : s-->'
		// +'					<div class="subMenuArea sub3" style="display: none;">'
		// +'					<div class="subMenuAreaWrap">'//[3/7: 수정]
		// +'						<div class="submenuTitle">'
		// +'							<p class="tit">보상/청구</p>'
		// +'							<p class="txt">접수부터 보험금 수령까지<br>간편하고 신속하게!</p>'
		// +'							<!--  strong><a href="/service.do?m=43e7038139"  ><img src="https://direct.hi.co.kr/images/common/gnb_04_1.gif" alt="접수부터 보험금 수령까지<br>간편하고 신속하게!" /></a></strong  -->'
		// +'						</div>'
		// +'						<ul class="gnb_dep2">'
		// +'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		// +'							<li class="on"><a href="/service.do?m=43e7038139">자동차사고/고장 접수</a>'
		// +'								<!-- 레벨 3 s-->'
		// +'								<ul class="gnb_dep3">'
		// +'									<li class="on"><a href="/service.do?m=43e7038139"><span>사고접수안내</span></a></li>'
		// +'									<li><a href="/service.do?m=19416bba17"><span>보험금청구서류</span></a></li>'
		// +'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100521" target="_blank" title="새창으로"><span>고장출동서비스</span></a></li>'
		// +'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100441" target="_blank" title="새창으로"><span>교통사고처리요령</span></a></li>'
		// +'								</ul>'
		// +'								<!-- 레벨 3 e-->'
		// +'							</li>'
		// +'							<!-- 레벨 2 e-->'
		// +'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		// +'							<li><a href="#" target="_blank" title="새창으로">보상상담</a>'
		// +'								<!-- 레벨 3 s-->'
		// +'								<ul class="gnb_dep3">'
		// +'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=100443" target="_blank" title="새창으로"><span>자동차보험 사고처리 유불리</span></a></li>'
		// +'								</ul>'
		// +'								<!-- 레벨 3 e-->'
		// +'							</li>'
		// +'							<!-- 레벨 2 e-->'
		// +'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		// +'							<li><a href="/service.do?m=d3a09d35d0">보험금 청구</a>'
		// +'								<!-- 레벨 3 s-->'
		// +'								<ul class="gnb_dep3">'
		// +'									<li><a href="/service.do?m=d3a09d35d0"><span>보험금청구안내</span></a></li>'
		// +'									<li><a href="/service.do?m=d3a09d35f0"><span>보험금청구서류</span></a></li>'
		// +'								</ul>'
		// +'								<!-- 레벨 3 e-->'
		// +'							</li>'
		// +'							<!-- 레벨 2 e-->'
		// +'						</ul>'
		// +'						<!-- bannerCall -->'
		// +'						<div class="gnBnCall ic_internet">'
		// +'							<div class="callCt">'
		// +'								<p class="txTi">'
		// +'									<strong>다이렉트 고객센터</strong>'
		// +'									<span>인터넷가입/계약변경</span>'
		// +'								</p>'
		// +'								<div class="txCall">'
		// +'									<strong class="cOrg">1899</strong><strong class="cBlue">-6782</strong>'
		// +'									<span>(평일9시~18시)</span>'
		// +'								</div>'
		// +'							</div>'
		// +'						</div>'
		// +'						<!-- // bannerCall -->'
		// +'					</div>'
		// +'					</div>'//[3/7: 수정] //subMenuAreaWrap
		// +'					<!--subMenuArea : e-->'
		// +'				</li>'


		+'				<li>'
		+'					<a href="/service.do?m=58ddb3faf8">혜택</a>'
		+'					<!--subMenuArea : s-->'
		+'					<div class="subMenuArea sub4" style="display: none;">'
		+'					<div class="subMenuAreaWrap">'//[3/7: 수정]
		+'						<div class="submenuTitle">'
		+'							<p class="tit">혜택/이벤트</p>'
		+'							<p class="txt">무이자 할부는 기본! <br>놓치기 쉬운 포인트 혜택까지</p>'
		+'							<!--  strong><a href="/service.do?m=58ddb3faf8"  ><img src="https://direct.hi.co.kr/images/common/gnb_03_1.gif" alt="무이자 할부는 기본! <br>놓치기 쉬운 포인트 혜택까지" /></a></strong  -->'
		+'						</div>'
		+'						<ul class="gnb_dep2 many">'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=58ddb3faf8">이달의 카드 할인/혜택</a></li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=98d21e6e26">포인트 결제</a></li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=34b8e0f086">이벤트</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=93b203359"><span>진행중 이벤트</span></a></li>'
		+'									<li><a href="/service.do?m=fe51010287"><span>당첨자 안내</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=1a4f675719">제휴사 할인/서비스</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=00a66ac167"><span>오토오아시스</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=7a52bef8bc">따뜻한 나눔</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=5b7d8a9c4a"><span>기부하기</span></a></li>'
		+'									<li><a href="/service.do?m=6999017849"><span>기부결과</span></a></li>'
		+'									<li><a href="/service.do?m=7044dbb403"><span>기부처소개</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=4215401386">다이렉트 TV</a></li>'
		+'							<!-- 레벨 2 e-->'
		+'						</ul>'
		+'						<!-- bannerCall -->'
		+'						<div class="gnBnCall ic_internet">'
		+'							<div class="callCt">'
		+'								<p class="txTi">'
		+'									<strong>다이렉트 고객센터</strong>'
		+'									<span>인터넷가입/계약변경</span>'
		+'								</p>'
		+'								<div class="txCall">'
		+'									<strong class="cOrg">1899</strong><strong class="cBlue">-6782</strong>'
		+'									<span>(평일9시~18시)</span>'
		+'								</div>'
		+'							</div>'
		+'						</div>'
		+'						<!-- // bannerCall -->'
		+'					</div>'
		+'					</div>'//[3/7: 수정] //subMenuAreaWrap
		+'					<!--subMenuArea : e-->'
		+'				</li>'


		+'				<li>'
		+'					<a href="/service.do?m=df1f1b2f16">이용안내</a>'
		+'					<!--subMenuArea : s-->'
		+'					<div class="subMenuArea sub5" style="display: none;">'
		+'					<div class="subMenuAreaWrap">'//[3/7: 수정]
		+'						<div class="submenuTitle">'
		+'							<p class="tit">고객센터</p>'
		+'							<p class="txt">고객님의 목소리에 귀 기울이는 현대해상 다이렉트입니다.</p>'
		+'							<!--  strong><a href="/service.do?m=df1f1b2f16"  ><img src="https://direct.hi.co.kr/images/common/gnb_02_1.gif" alt="고객님의 목소리에 귀 기울이는 현대해상 다이렉트입니다." /></a></strong  -->'
		+'						</div>'
		+'						<ul class="gnb_dep2 many">'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="#">고객의 소리</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=304e3b0d8e"><span>고객체험후기</span></a></li>'
		+'									<li><a href="/service.do?m=fc452654c6"><span>이메일 상담신청</span></a></li>'
		+'									<li><a href="https://www.hi.co.kr/serviceAction.do?menuId=101451"><span>전자민원 접수</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="#">고객 안내사항</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=b79d5eefe8"><span>FAQ (자주 묻는 질문)</span></a></li>'
		+'									<li><a href="/service.do?m=1dc3a3a380"><span>공지사항</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="#">모바일 이용안내</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=fdaf815390"><span>모바일 서비스</span></a></li>'
		+'									<li><a href="/service.do?m=47f30812c0"><span>보험료계산 가이드</span></a></li>'
		+'									<li><a href="/service.do?m=47f30812c1"><span>보안프로그램 설치 및 안내</span></a></li>'
		+'									<li><a href="/service.do?m=b11cacddee"><span>공동인증서 이용안내</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=47f30812bf">고객콜센터 안내</a></li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="/service.do?m=bfda6eb660">상담원 채용</a></li>'
		+'							<!-- 레벨 2 e-->'
		+'							<!-- 레벨 2 s--><!-- P20200917-0056   심흥무 -->'
		+'							<li><a href="#">홈페이지 이용안내</a>'
		+'								<!-- 레벨 3 s-->'
		+'								<ul class="gnb_dep3">'
		+'									<li><a href="/service.do?m=f783053a96"><span>보험료계산 가이드</span></a></li>'
		+'									<li><a href="/service.do?m=1e5bcd6ec7"><span>실시간 상담 신청 가이드</span></a></li>'
		+'									<li><a href="/service.do?m=6799759c25"><span>보안프로그램 설치 및 안내</span></a></li>'
		+'									<li><a href="/service.do?m=47f30812c2"><span>전자금융거래 유의사항</span></a></li>'
		+'								</ul>'
		+'								<!-- 레벨 3 e-->'
		+'							</li>'
		+'							<!-- 레벨 2 e-->'
		+'						</ul>'
		+'						<!-- bannerCall -->'
		+'						<div class="gnBnCall ic_internet">'
		+'							<div class="callCt">'
		+'								<p class="txTi">'
		+'									<strong>다이렉트 고객센터</strong>'
		+'									<span>인터넷가입/계약변경</span>'
		+'								</p>'
		+'								<div class="txCall">'
		+'									<strong class="cOrg">1899</strong><strong class="cBlue">-6782</strong>'
		+'									<span>(평일9시~18시)</span>'
		+'								</div>'
		+'							</div>'
		+'						</div>'
		+'						<!-- // bannerCall -->'
		+'					</div>'
		+'					</div>'//[3/7: 수정] //subMenuAreaWrap
		+'					<!--subMenuArea : e-->'
		+'				</li>'
		+'			</ul>'
		+'		</div>'
		+'	</div>'
		+'</div>'
		+'<!--gnbWrapSet : e-->'
	;
	
	document.write(str);

  
})();

