(function(){
	var str='';
str+= '<div class="gnb-top"> ';
str+= '<div class="top-inner">';
str+= '	<ul class="links">';
str+= '		<li><a href="#">회사소개</a></li>';
str+= '		<li class="current"><a href="#">책임투자</a></li>';
str+= '		<li><a href="#">KOSEF</a></li>';
str+= '	</ul>';
str+= '	<a href="#" class="link-global"><span>ENG</span></a>';
str+= '</div>';
str+= '</div>';
str+= '<div class="gnb-nav">';
str+= '<div class="gnb-inner">';
str+= '	<h1><a href="#" class="logo"><span class="hide">키움투자자산운용</span></a></h1>';
str+= '	<div class="gnb">';
str+= '		<nav>';
str+= '			<ul class="menu">';
str+= '				<li><a href="#">펀드상품</a>    ';                                                      
str+= '					<ul class="sub">';
str+= '						<li><a href="#">키움펀드맵</a></li>';
str+= '						<li><a href="#">펀드찾기</a></li>';
str+= '						<li><a href="#">분할매수상품</a></li>';
str+= '					</ul>     ';                    
str+= '				</li>';
str+= '				<li><a href="#">연금</a>';
str+= '					<ul class="sub">';
str+= '						<li><a href="#none">TDF</a></li>';
str+= '						<li><a href="#none">OCIO</a></li>';
str+= '						<li><a href="#none">연금펀드</a></li>';
str+= '						<li><span>연금아카데미</span> <!-- 20230404 링크 없을경우 span 으로 수정 -->';
str+= '							<ul>';
str+= '								<li><a href="#none">퇴직연금제도</a></li>';
str+= '								<li><a href="#none">개인연금제도</a></li>';
str+= '								<li><a href="#none">연금투자방법</a></li>';
str+= '								<li><a href="#none">MZ 연금레터</a></li>  ';                                  
str+= '							</ul>';
str+= '						</li>  ';
str+= '					</ul>     ';                           
str+= '				</li>';
str+= '				<li><a href="#">대체투자</a>';
str+= '					<ul class="sub">';
str+= '						<li><a href="#">REITS</a></li>';
str+= '						<li><a href="#">포트폴리오</a></li>';
str+= '					</ul>';
str+= '				</li>';
str+= '				<li><a href="#" class="current">키움라운지</a>';
str+= '					<ul class="sub">';
str+= '						<li><a href="#none">회사소개</a></li>';
str+= '						<li><span class="current">투자정보</span>';
str+= '							<ul>';
str+= '								<li><a href="#none" class="current">키자 매거진</a></li>';
str+= '								<li><a href="#none">키자 TV</a></li>';
str+= '								<li><a href="#none">키움 뉴스</a></li>';
str+= '								<li><a href="#none">이벤트</a></li>  ';                                  
str+= '							</ul>';
str+= '						</li>';
str+= '						<li><span href="#none">책임투자</span>';
str+= '							<ul>';
str+= '								<li><a href="#none">키움 ESG</a></li>';
str+= '								<li><a href="#none">스튜어드십코드</a></li>     ';                               
str+= '							</ul>';
str+= '						</li>';
str+= '						<li><a href="#none">인재채용</a></li>    ';  
str+= '					</ul>     ';                           
str+= '				</li>';
str+= '				<li><a href="#">공시</a>';
str+= '					<ul class="sub">';
str+= '						<li><a href="#none">경영공시</a></li>               ';
str+= '						<li><a href="#none">펀드공시</a></li>               ';                     
str+= '						<li><a href="#none">파생공시</a></li>               ';                     
str+= '						<li><a href="#none">리츠공시</a></li>               ';                     
str+= '						<li><a href="#none">손실예상금액공시</a></li>       ';                             
str+= '						<li><a href="#none">연금저축펀드비교공시</a></li>   ';                                 
str+= '						<li><a href="#none">스튜어드십코드공시</a></li>     ';                               
str+= '						<li><a href="#none">고난도금융투자상품</a></li>  ';
str+= '					</ul>   ';                            
str+= '				</li>';
str+= '			</ul>  ';             
str+= '		</nav>';
str+= '	</div>     ';           
str+= '	<!-- search -->';
str+= '	<div class="top-sch-group">';
str+= '		<button class="btn-sch"><span class="hide">검색</span></button>';
str+= '		<div class="sch-cont" tabindex="-1">';
str+= '			<div class="search-area">';
str+= '				<div class="sch-top">';
str+= '					<input type="text" class="inp-base" data-clear="true" placeholder="상품명을 입력하세요." title="상품명 입력"> <!-- 20230213 수정 -->';
str+= '					<button class="btn-sch"><span class="hide">펀드 검색</span></button>';
str+= '				</div>';
str+= '				<dl class="sch-tips">';
str+= '					<dt>추천검색어</dt>';
str+= '					<dd>';
str+= '						<button type="button" class="active">#ESG</button>';
str+= '						<button type="button">#미국</button>';
str+= '						<button type="button">#원자재</button>';
str+= '						<button type="button">#신흥국</button>';
str+= '						<button type="button">#인플레이션</button>';
str+= '					</dd>';
str+= '				</dl>';
str+= '			</div>';
str+= '			<button type="button" class="btn-close"><span class="hide">닫기</span></button>';
str+= '		</div>';
str+= '	</div> ';   
str+= '	<!-- //search -->   ';              
str+= '</div>';
str+= '<div class="gnb-bg"></div>';
str+= '</div>';


	document.write(str);
})();

