/**
* 기업 : 퇴직연금 
* ------------------
* header.js
*/

(function(){
	var str='';
		str+='<div class="header_top">';
		str+='	<div class="inner">';
		str+='		<div class="m_bridge">';
		str+='			<a href="#none">대표</a>';
		str+='			<a href="#none">기업</a>';
		str+='			<a href="#none">적하</a>';
		str+='			<a href="#none" class="on" title="현재선택">퇴직연금</a>';
		str+='			<a href="#none" class="direct">다이렉트</a>';
		str+='		</div>';
		str+='		<div class="snb">';
		str+='			<div class="use_time">';
		str+='				<span class="time_box">20:00</span>';
		str+='				<button type="button" class="b_time"><span>시간연장</span></button>';
		str+='			</div>';
		str+='			<ul class="quick_link">';
		str+='				<li><a href="#none">로그아웃</a></li>';
		str+='				<li><a href="#none">마이페이지</a></li>';
		str+='				<li><a href="#none">사이트맵</a></li>';
		str+='			</ul>';
		str+='			</div>';
		str+='	</div>';
		str+='</div>';
		str+='<div class="header_gnb">';
		str+='	<div class="inner">';
		str+='		<h1><a href="#" title="퇴직연금 홈으로 이동하기"><span class="offscr">현대해상</span><span class="bridge_name">퇴직연금</span></a></h1>';
		str+='		<div class="user_type">';
		str+='				홍길동님은 <strong>확정급여형제도</strong>의 가입자입니다.';
		str+='		</div>';
		str+='		<h2 class="offscr">주요메뉴</h2>';
		str+='		<nav class="gnb">';
		str+='			<ul>';
		str+='				<li><a href="#" data-menuid="RMPG10000M"><span>퇴직연금가이드</span></a></li>';
		str+='				<li><a href="#" data-menuid="RMPS10000M"><span>가입자서비스</span></a></li>';
		str+='				<li><a href="#" data-menuid="RMSC10000M"><span>스마트발급센터</span></a></li>';
		str+='				<li><a href="#"><span>고객지원센터</span></a></li>';
		str+='			</ul>';
		str+='		</nav>';
		str+='	</div>';
		str+='	<div class="gnb_sub">';
		str+='		<dl>';
		str+='			<div class="part1">';
		str+='				<dd class="sub1">';
		str+='					<h3 data-menuid="RMPG01000M">제도소개</h3>';
		str+='					<a href="#none" data-menuid="RMPG01010M">제도안내</a>';
		str+='					<a href="#none" data-menuid="RMPG01020M">연금가이드</a>';
		str+='					<a href="#none" data-menuid="RMPG01030M">연금설계시뮬레이션</a>';
		str+='					<a href="#none" data-menuid="RMPG01040M">가입자교육안내</a>';
		str+='					<a href="#none" data-menuid="RMPG01050M">Hi~ My 현대해상</a>';
		str+='					<a href="#none" data-menuid="RMPG01055M">국제회계기준안내</a>';
		str+='					<h3 data-menuid="RMPG02000M">상품정보</h3>';
		str+='					<a href="#none" data-menuid="RMPG02010M">상품안내</a>';
		str+='					<a href="#none" data-menuid="RMPG02030M">투자성향진단</a>';
		str+='				</dd>';
		str+='				<dd class="sub2">';
		str+='					<div class="sub2_part1">';
		str+='						<h3 data-menuid="RMPS01000M">계약정보</h3>';
		str+='						<a href="#none" data-menuid="RMPS01010M">계약전체보기</a>';
		str+='						<a href="#none" data-menuid="RMPS01020M">계약기본정보</a>';
		str+='						<a href="#none" data-menuid="RMPS01030M">고객정보변경</a>';
		str+='						<a href="#none" data-menuid="RMPS01040M">가입자명부조회</a>';
		str+='						<h3 data-menuid="RMPS02000M">운용현황</h3>';
		str+='						<a href="#none" data-menuid="RMPS02059M">거래내역</a>';
		str+='						<a href="#none" data-menuid="RMPS02130M">수수료</a>';
		str+='						<a href="#none" data-menuid="RMPS02140M">적립금현황</a>';
		str+='						<a href="#none" data-menuid="RMPS02150M">만기대상조회</a>';
		str+='						<a href="#none" data-menuid="RMPS02160M">만기결과조회</a>';
		str+='						<h3 data-menuid="RMPS04000M">가입자 교육</h3>';
		str+='						<a href="#none" data-menuid="RMPS04010M">교육안내</a>';
		str+='						<a href="#none" data-menuid="RMPS04020M">강의진도</a>';
		str+='						<a href="#none" data-menuid="RMPS04030M">강의실</a>';
		str+='						<a href="#none" data-menuid="RMPS04070M">두근두근 은퇴설계</a>';
		str+='						<a href="#none" data-menuid="RMPS04100M">교육현황</a>';
		str+='					</div>';
		str+='					<div class="sub2_part2">';
		str+='						<h3 data-menuid="RMPS03000M">신청/변경/해지</h3>';
		str+='						<a href="#none" data-menuid="RMPS03010M">기업정보변경</a>';
		str+='						<a href="#none" data-menuid="RMPS03020M">투자성향진단</a>';
		str+='						<a href="#none" data-menuid="RMPS03080M">투자성향등록내역</a>';
		str+='						<a href="#none" data-menuid="RMPS03089M">상품라인업/<br/>부담금투입비율</a>';
		str+='						<a href="#none" data-menuid="RMPS03130M">운용자산변경</a>';
		str+='						<a href="#none" data-menuid="RMPS03170M">IRP계약해지신청</a>';
		str+='						<a href="#none" data-menuid="RMPS03190M">연금계좌납입한도설정/<br/>자동이체변경</a>';
		str+='						<a href="#none" data-menuid="RMPS03200M">추가가입신청</a>';
		str+='						<a href="#none" data-menuid="RMPS03210M">기준급여/추계액변경</a>';
		str+='						<a href="#none" data-menuid="RMPS03220M">결재관리</a>';
		str+='						<a href="#none" data-menuid="RMPS03230M">DC예비가입신청</a>';
		str+='						<a href="#none" data-menuid="RMPS01050M">연금개시신청</a>';
		str+='						<a href="#none" data-menuid="RMPG01060M">IRP 전자청약</a>';
		str+='						<a href="#none" data-menuid="RMPG01130M">연금계좌 이체신청</a>';
		str+='					</div>';
		str+='				</dd>';
		str+='			</div>';
		str+='			<div class="part2">';
		str+='				<dd class="sub3">';
		str+='					<h3><a href="#none" data-menuid="RMSC01010M">신청서 다운로드</a></h3>';
		str+='					<h3><a href="#none" data-menuid="RMSC01020M">증명서 발급</a></h3>';
		str+='				</dd>';
		str+='				<dd class="sub4">';
		str+='					<h3><a href="#none" data-menuid="RMCS01010M">공지사항</a></h3>';
		str+='					<h3><a href="#none" data-menuid="RMCS01020M">자주 하는 질문</a></h3>';
		str+='					<h3><a href="#none" data-menuid="RMCS01030M">상담신청</a></h3>';
		str+='					<h3><a href="#none" data-menuid="RMCS01040M">나의 상담내역</a></h3>';
		str+='					<h3><a href="#none" data-menuid="RMCS01050M">자료실</a></h3>';
		str+='					<h3 data-menuid="RMCS20000M">인증센터</h3>';
		str+='					<a href="#none" data-menuid="RMCS02010M">공동인증서 등록/변경/취소</a>';
		str+='					<a href="#none" data-menuid="RMCS03010M">금융인증서 등록/변경/삭제</a>';
		str+='					<h3 data-menuid="RMCS40000M">보안센터</h3>';
		str+='					<a href="#none" data-menuid="RMCS04010M">보안프로그램 안내</a>';
		str+='					<a href="#none" data-menuid="RMCS04020M">보안프로그램 설치</a>';
		str+='				</dd>';
		str+='			</div>';
		str+='		</dl>';
		str+='	</div>';
		str+='</div>';
	document.write(str);
})();
