/**
* 다이렉트 보험 서비스 플랫폼 구축
* ------------------------------
* detail_overseastrip.js
*/

(function(){
	var str=''
					+'<aside id="detailSidebar" class="sidebar detail_sidebar" data-role="global-navigation" aria-hidden="true">'
					+'	<div class="sidebar_wrap">'
					+'		<div class="sidebar_top">'
					+'			<button type="button" class="btn_sidebar_close prev" aria-label="상세 메뉴 닫기"></button>'
					+'			<h2 class="header-title">해외여행보험 상세정보</h2> '
					+'			<button type="button" class="btn_sidebar_close blind" aria-label="메뉴 닫기" aria-hidden="true"></button>'
					+'		</div>'
					+'		<div class="sidebar_content">'
					+'			<div class="content_wrap">'
					+'				<div class="section">'
					+'					<div class="comp">'
					+'						<!-- 프로세스 스탭 클래스 가이드 .complete 완료/ .ing 진행 중 -->'
					+'						<div class="list_detail_info">'
					+'							<ul>'
					+'								<li class="box complete">'
					+'									<div class="item_top">'
					+'										<i class="icon num" data-icon="num01"><span class="blind">1번째 스텝</span></i>'
					+'										<strong class="tit">기본정보</strong>'
					+'										<a href="#none" class="btn text">수정</a>'
					+'										<span class="ing_txt">진행 중</span>'
					+'									</div>'
					+'									<div class="item_txt">'
					+'										<span>1996.01.06</span>'
					+'										<span>남성</span>'
					+'										<span>2023.05.01(7시)~2023.05.05(21시)</span>'
					+'									</div>'
					+'								</li>'
					+'								<li class="box complete">'
					+'									<div class="item_top">'
					+'										<i class="icon num" data-icon="num02"><span class="blind">2번째 스텝</span></i>'
					+'										<strong class="tit">계약자/피보험자 정보</strong>'
					+'										<a href="#none" class="btn text">수정</a>'
					+'										<span class="ing_txt">진행 중</span>'
					+'									</div>'
					+'									<div class="item_txt">'
					+'										<span>1996.01.06</span>'
					+'										<span>남성</span>'
					+'									</div>'
					+'								</li>'
					+'								<li class="box complete">'
					+'									<div class="item_top">'
					+'										<i class="icon num" data-icon="num03"><span class="blind">3번째 스텝</span></i>'
					+'										<strong class="tit">보험료 확인</strong>'
					+'										<a href="#none" class="btn text">수정</a>'
					+'										<span class="ing_txt">진행 중</span>'
					+'									</div>'
					+'									<div class="item_txt">'
					+'										<span>프리미엄 플랜</span>'
					+'										<span>25,000원</span>'
					+'									</div>'
					+'								</li>'
					+'								<li class="box complete">'
					+'									<div class="item_top">'
					+'										<i class="icon num" data-icon="num04"><span class="blind">4번째 스텝</span></i>'
					+'										<strong class="tit">계약자정보</strong>'
					+'										<a href="#none" class="btn text">수정</a>'
					+'										<span class="ing_txt">진행 중</span>'
					+'									</div>'
					+'									<div class="item_txt">'
					+'										<span>하*현(123456-2******)</span>'
					+'										<span>2023.05.01(7시)~2023.05.05(21시)</span>'
					+'										<span>HA *** HYUN</span>'
					+'									</div>'
					+'								</li>'
					+'								<li class="box ing">'
					+'									<div class="item_top">'
					+'										<i class="icon num" data-icon="num05"><span class="blind">5번째 스텝</span></i>'
					+'										<strong class="tit">가입 전 알릴 사항</strong>'
					+'										<a href="#none" class="btn text">수정</a>'
					+'										<span class="ing_txt">진행 중</span>'
					+'									</div>'
					+'									<div class="item_txt">'
					+'										<span>하*현(123456-2******)</span>'
					+'										<span>HA *** HYUN 외 2명</span>'
					+'									</div>'
					+'								</li>'
					+'								<li class="box">'
					+'									<div class="item_top">'
					+'										<i class="icon num" data-icon="num06"><span class="blind">6번째 스텝</span></i>'
					+'										<strong class="tit">청약내용 확인</strong>'
					+'										<a href="#none" class="btn text">수정</a>'
					+'										<span class="ing_txt">진행 중</span>'
					+'									</div>'
					+'									<div class="item_txt">'
					+'										<span>다이렉트 해외여행보험</span>'
					+'									</div>'
					+'								</li>'
					+'								<li class="box">'
					+'									<div class="item_top">'
					+'										<i class="icon num" data-icon="num07"><span class="blind">7번째 스텝</span></i>'
					+'										<strong class="tit">보험료결제</strong>'
					+'										<a href="#none" class="btn text">수정</a>'
					+'										<span class="ing_txt">진행 중</span>'
					+'									</div>'
					+'									<div class="item_txt">'
					+'										<span>미국</span>'
					+'										<span>2023.05.01(7시)~2023.05.05(21시)</span>'
					+'									</div>'
					+'								</li>'
					+'							</ul>'
					+'						</div>'
					+'					</div>'
					+'				</div>'
					+'			</div>'
					+'			<div class="content_footer fix">'
					+'				<div class="btn_area footer cta type02">'
					+'					<button type="button" class="btn fill02">홈으로</button>'
					+'					<button type="button" class="btn fill01">계속 진행하기</button>'
					+'				</div>'
					+'			</div>'
					+'			<div class="chartbot_area">'
					+'				<a href="#none" target="_blank" class="chatbot"><span class="blind">챗봇상담</span></a>'
					+'			</div>'
					+'		</div>'
					+'	</div>'
					+'</aside>'

	document.write(str);
})();

